# Generated by Django 4.1.3 on 2022-12-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('exerciseId', models.BigAutoField(primary_key=True, serialize=False)),
                ('exerciseName', models.CharField(max_length=50)),
                ('exerciseType', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female')], max_length=20)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
    ]
